namespace MatchAnalyzer.Api.Models;

public class Match
{
    public int Id { get; set; }
    public string HomeTeam { get; set; } = string.Empty;
    public string AwayTeam { get; set; } = string.Empty;
    public DateTime? Date { get; set; }
    public string? Score { get; set; }
    public int? GoalsCount { get; set; }
    public int? FirstHalfGoals { get; set; }
    public bool IsParsed { get; set; }
    
    public string MatchId { get; set; } = string.Empty;
    
    public string HomeTeamId { get; set; } = string.Empty;
    public string AwayTeamId { get; set; } = string.Empty;

    public bool IsFavorite05 { get; set; }
    public bool IsFavorite15 { get; set; }
    public bool IsFavoriteFH05 { get; set; }
    public bool IsFavoriteFH15 { get; set; } 
    
    public double? Over25Odds { get; set; }
    public double? Under25Odds { get; set; }
}

public class AIPredictionsLog
{
    public int Id { get; set; }
    public string MatchId { get; set; }

    public string HomeTeam { get; set; }
        
    public string AwayTeam { get; set; }

    // The date and time the match is scheduled to be played
    public DateTime Date { get; set; }

    // Mapped exactly to the column name generated by the Python script
    public double AI_Over25_Prob { get; set; }

    // The exact timestamp of when the AI made this prediction
    public DateTime PredictedOn { get; set; }
    public string Model { get; set;}
    
}
